<?php
/**
 * Excel export for the university sports committee.
 *
 * GET params:
 *   ?id=123   -> export a single student (one row, with header)
 *   (none)    -> export all students in the current scope
 *
 * Output: .xls (SpreadsheetML 2003 XML — opens in Excel, LibreOffice, Google Sheets)
 * No external libraries; pure XML.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/bootstrap.php';
require_login();
require_department();

$me = current_faculty();
$single_id = (int)($_GET['id'] ?? 0);
$is_single = $single_id > 0;

/* ---------------- load scope data ---------------- */

$college = db_one('SELECT * FROM college_settings WHERE id = 1') ?? [
    'name' => 'YSPM Yashoda Technical Campus',
    'address' => '',
];

$rows = [];
$where_extra = '';
$extra_params = [];
$extra_types  = '';

if ($is_single) {
    [$scope, $p, $t] = scope_sql_department('s');
    $rows = db_select(
        "SELECT s.*, d.name AS dept_name
           FROM students s
           JOIN departments d ON d.id = s.department_id
          WHERE s.id = ? $scope",
        array_merge([$single_id], $p), 'i' . $t
    );
    if (!$rows) {
        http_response_code(404);
        exit('Student not found.');
    }
} else {
    [$scope, $p, $t] = scope_sql_department('s');
    $params = $p;
    $types  = $t;

    $q  = trim((string)($_GET['q'] ?? ''));
    $ay = trim((string)($_GET['academic_year'] ?? ''));
    $sy = trim((string)($_GET['study_year'] ?? ''));

    if ($q !== '') {
        $where_extra .= ' AND (s.enrollment_no LIKE ? OR s.full_name LIKE ?) ';
        $params[] = '%' . $q . '%';
        $params[] = '%' . $q . '%';
        $types   .= 'ss';
    }
    if ($ay !== '') {
        $where_extra .= ' AND s.academic_year = ? ';
        $params[] = $ay;
        $types   .= 's';
    }
    if ($sy !== '') {
        $where_extra .= ' AND s.study_year = ? ';
        $params[] = $sy;
        $types   .= 's';
    }

    $rows = db_select(
        "SELECT s.*, d.name AS dept_name
           FROM students s
           JOIN departments d ON d.id = s.department_id
          WHERE 1=1 $scope $where_extra
          ORDER BY s.enrollment_no",
        $params, $types
    );
}

$dept_label = $is_single
    ? ($rows[0]['dept_name'] ?? '—')
    : ($me['department_name'] ?? 'All Departments');

$generated_at = date('d M Y, H:i');
$generated_by = $me['full_name'];
$total = count($rows);

/* ---------------- build XML ---------------- */

function xml_escape($s): string {
    if ($s === null) return '';
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_XML1, 'UTF-8');
}

function xml_cell($value, $type = 'String', $styleId = null): string {
    $s = $styleId !== null ? ' ss:StyleID="' . $styleId . '"' : '';
    $v = xml_escape($value);
    return "<Cell$s><Data ss:Type=\"$type\">$v</Data></Cell>";
}

$styles = '
<Styles>
  <Style ss:ID="Title">
    <Font ss:Bold="1" ss:Size="14"/>
    <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="Header">
    <Font ss:Bold="1" ss:Color="#FFFFFF"/>
    <Interior ss:Color="#1A365D" ss:Pattern="Solid"/>
    <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Top"    ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="1"/>
    </Borders>
  </Style>
  <Style ss:ID="Data">
    <Alignment ss:Vertical="Top" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="0.5"/>
    </Borders>
  </Style>
  <Style ss:ID="Label">
    <Font ss:Bold="1"/>
    <Alignment ss:Horizontal="Right" ss:Vertical="Top"/>
  </Style>
</Styles>';

// Header block rows
$header_block = '';
$ay_label = 'All';
if ($is_single) {
    $ay_label = (string)($rows[0]['academic_year'] ?? '');
} elseif (isset($ay) && $ay !== '') {
    $ay_label = $ay;
}
$header_rows = [
    ['College',       $college['name']],
    ['Department',    $dept_label],
    ['Academic Year', $ay_label],
    ['Generated On',  $generated_at],
    ['Generated By',  $generated_by],
    ['Total Students', $total],
];
foreach ($header_rows as $hr) {
    $header_block .= '<Row>'
        . xml_cell($hr[0], 'String', 'Label')
        . xml_cell($hr[1], 'String')
        . '</Row>';
}

// Column headers
$columns = [
    'Sr. No.', 'Enrollment No.', 'Full Name', 'Gender', 'Date of Birth',
    'Blood Group', 'Email', 'Mobile', "Parent's Phone", 'Address',
    'Program / Branch', 'Academic Year', 'Year of Study',
    'Primary Sport', 'Secondary Sport', 'Sports History', 'Achievements',
];
$col_header_row = '<Row ss:Height="30">';
foreach ($columns as $col) {
    $col_header_row .= xml_cell($col, 'String', 'Header');
}
$col_header_row .= '</Row>';

// Data rows
$data_rows = '';
$sr = 1;
foreach ($rows as $r) {
    $dob = $r['dob'] ? date('d-m-Y', strtotime($r['dob'])) : '';
    $data_rows .= '<Row>';
    $data_rows .= xml_cell($sr++, 'Number', 'Data');
    $data_rows .= xml_cell($r['enrollment_no'], 'String', 'Data');
    $data_rows .= xml_cell($r['full_name'],     'String', 'Data');
    $data_rows .= xml_cell($r['gender'] ?? '',  'String', 'Data');
    $data_rows .= xml_cell($dob,                'String', 'Data');
    $data_rows .= xml_cell($r['blood_group'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['email'] ?? '',   'String', 'Data');
    $data_rows .= xml_cell($r['mobile'] ?? '',  'String', 'Data');
    $data_rows .= xml_cell($r['parent_phone'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['address'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['program'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['academic_year'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['study_year'] ?? '',    'String', 'Data');
    $data_rows .= xml_cell($r['sport_1'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['sport_2'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['sports_history'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell($r['achievements'] ?? '', 'String', 'Data');
    $data_rows .= '</Row>';
}

// Column widths
$widths = [55, 110, 180, 70, 100, 80, 180, 110, 110, 200, 180, 100, 90, 130, 130, 260, 260];
$cols_xml = '';
foreach ($widths as $i => $w) {
    $cols_xml .= '<Column ss:Index="' . ($i + 1) . '" ss:Width="' . $w . '"/>';
}

$xml = '<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
' . $styles . '
<Worksheet ss:Name="Students">
<Table>
' . $cols_xml . $header_block . $col_header_row . $data_rows . '
</Table>
</Worksheet>
</Workbook>';

/* ---------------- send headers ---------------- */

$filename = $is_single
    ? 'student_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $rows[0]['enrollment_no']) . '_' . date('Ymd') . '.xls'
    : 'students_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $dept_label) . '_' . date('Ymd') . '.xls';

header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

// BOM so Excel opens UTF-8 correctly
echo "\xEF\xBB\xBF" . $xml;
