<?php
/**
 * Excel export for a provisional player list.
 *
 * GET params:
 *   game   string  the game name (required)
 *   event  string  the event label (required)
 *   ay     string  the academic year (optional)
 *
 * Output: .xls (SpreadsheetML 2003 XML — opens in Excel, LibreOffice, Google Sheets)
 * No external libraries; pure XML.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/bootstrap.php';
require_login();
require_department();

$me    = current_faculty();
$game  = trim((string)($_GET['game'] ?? ''));
$event = trim((string)($_GET['event'] ?? ''));
$ay    = trim((string)($_GET['ay'] ?? ''));

if ($game === '' || $event === '') {
    http_response_code(400);
    exit('Game and event label are required.');
}

/* ---------------- load scope data ---------------- */

$college = db_one('SELECT * FROM college_settings WHERE id = 1') ?? [
    'name'    => 'YSPM Yashoda Technical Campus',
    'address' => '',
];

[$scope, $p, $t] = scope_sql_department('s');

$rows = db_select(
    "SELECT pe.id AS entry_id, pe.notes, pe.created_at AS added_at,
            s.id, s.enrollment_no, s.full_name,
            s.gender, s.dob, s.blood_group,
            s.email, s.mobile, s.parent_phone, s.address,
            s.program, s.academic_year, s.study_year,
            s.sport_1, s.sport_2, s.sports_history,
            d.name AS dept_name
       FROM provisional_entries pe
       JOIN students s    ON s.id = pe.student_id
       JOIN departments d ON d.id = s.department_id
      WHERE pe.game_name = ?
        AND pe.event_label = ?
        AND pe.academic_year <=> ?
        $scope
      ORDER BY pe.created_at ASC, s.enrollment_no ASC",
    array_merge([$game, $event, $ay === '' ? null : $ay], $p), 'sss' . $t
);

if (!$rows) {
    http_response_code(404);
    exit('No players found for this list.');
}

$dept_label   = $me['department_name'] ?? 'All Departments';
$generated_at = date('d M Y, H:i');
$generated_by = $me['full_name'];
$total        = count($rows);

/* ---------------- build XML ---------------- */

function xml_escape_prov($s): string {
    if ($s === null) return '';
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_XML1, 'UTF-8');
}

function xml_cell_prov($value, $type = 'String', $styleId = null): string {
    $s = $styleId !== null ? ' ss:StyleID="' . $styleId . '"' : '';
    $v = xml_escape_prov($value);
    return "<Cell$s><Data ss:Type=\"$type\">$v</Data></Cell>";
}

$styles = '
<Styles>
  <Style ss:ID="Title">
    <Font ss:Bold="1" ss:Size="14"/>
    <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="Header">
    <Font ss:Bold="1" ss:Color="#FFFFFF"/>
    <Interior ss:Color="#1A365D" ss:Pattern="Solid"/>
    <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Top"    ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="1"/>
    </Borders>
  </Style>
  <Style ss:ID="Data">
    <Alignment ss:Vertical="Top" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="0.5"/>
    </Borders>
  </Style>
  <Style ss:ID="Label">
    <Font ss:Bold="1"/>
    <Alignment ss:Horizontal="Right" ss:Vertical="Top"/>
  </Style>
</Styles>';

// Header block rows
$header_rows = [
    ['College',        $college['name']],
    ['Department',     $dept_label],
    ['Game / Sport',   $game],
    ['Event',          $event],
    ['Academic Year',  $ay !== '' ? $ay : 'Any'],
    ['Generated On',   $generated_at],
    ['Generated By',   $generated_by],
    ['Total Players',  $total],
];
$header_block = '';
foreach ($header_rows as $hr) {
    $header_block .= '<Row>'
        . xml_cell_prov($hr[0], 'String', 'Label')
        . xml_cell_prov($hr[1], 'String')
        . '</Row>';
}

// Blank spacer row
$header_block .= '<Row></Row>';

// Column headers
$columns = [
    'Sr. No.', 'Enrollment No.', 'Full Name', 'Gender', 'Date of Birth',
    'Blood Group', 'Email', 'Mobile', "Parent's Phone", 'Address',
    'Program / Branch', 'Department', 'Academic Year', 'Year of Study',
    'Primary Sport', 'Secondary Sport', 'Sports History', 'Notes',
];
$col_header_row = '<Row ss:Height="30">';
foreach ($columns as $col) {
    $col_header_row .= xml_cell_prov($col, 'String', 'Header');
}
$col_header_row .= '</Row>';

// Data rows
$data_rows = '';
$sr = 1;
foreach ($rows as $r) {
    $dob = !empty($r['dob']) ? date('d-m-Y', strtotime($r['dob'])) : '';
    $data_rows .= '<Row>';
    $data_rows .= xml_cell_prov($sr++, 'Number', 'Data');
    $data_rows .= xml_cell_prov($r['enrollment_no'], 'String', 'Data');
    $data_rows .= xml_cell_prov($r['full_name'],     'String', 'Data');
    $data_rows .= xml_cell_prov($r['gender'] ?? '',  'String', 'Data');
    $data_rows .= xml_cell_prov($dob,                'String', 'Data');
    $data_rows .= xml_cell_prov($r['blood_group'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['email'] ?? '',   'String', 'Data');
    $data_rows .= xml_cell_prov($r['mobile'] ?? '',  'String', 'Data');
    $data_rows .= xml_cell_prov($r['parent_phone'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['address'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['program'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['dept_name'],     'String', 'Data');
    $data_rows .= xml_cell_prov($r['academic_year'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['study_year'] ?? '',    'String', 'Data');
    $data_rows .= xml_cell_prov($r['sport_1'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['sport_2'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['sports_history'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['notes'] ?? '',   'String', 'Data');
    $data_rows .= '</Row>';
}

// Column widths
$widths = [55, 110, 180, 70, 100, 80, 180, 110, 110, 200, 180, 140, 100, 90, 130, 130, 260, 200];
$cols_xml = '';
foreach ($widths as $i => $w) {
    $cols_xml .= '<Column ss:Index="' . ($i + 1) . '" ss:Width="' . $w . '"/>';
}

$sheet_name = mb_substr("Provisional - $game", 0, 31); // Excel max sheet name = 31 chars

$xml = '<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
' . $styles . '
<Worksheet ss:Name="' . xml_escape_prov($sheet_name) . '">
<Table>
' . $cols_xml . $header_block . $col_header_row . $data_rows . '
</Table>
</Worksheet>
</Workbook>';

/* ---------------- send headers ---------------- */

$safe_game  = preg_replace('/[^A-Za-z0-9_-]/', '_', $game);
$safe_event = preg_replace('/[^A-Za-z0-9_-]/', '_', $event);
$filename   = 'provisional_' . $safe_game . '_' . $safe_event . '_' . date('Ymd') . '.xls';

header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

// BOM so Excel opens UTF-8 correctly
echo "\xEF\xBB\xBF" . $xml;
